### ISSUE TITLE
Global vs hopeful stability testing

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#88] opened 2017-09-27 19:59 UTC
Sometimes we assume that a model is stable, and we want to know if the single stable point is interior or on the axes. That can be done by checking a single point.

Sometimes we want to check that the model IS stable (for all points).

**Comment by kmclaren-trinity** [comment] 2018-06-07 20:55
Duplicate of #87

**Closed by kmclaren-trinity** 2018-06-07 20:55 UTC
